# GraphQL Federation Gateway - Go Linter Configuration
# Strict quality gates for production-ready code

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - src-typescript-backup
  skip-files:
    - ".*_test.go"
    - "test/fixtures/.*"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/erpmicroservices

  golint:
    min-confidence: 0.8

  govet:
    check-shadowing: true
    enable-all: true

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  unparam:
    check-exported: false

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-case-traling-whitespace: true
    allow-cuddle-declarations: false

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Additional quality linters
    - asciicheck
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    # Exclude some lints from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
        - goconst
        - gomnd

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude some gosec messages
    - linters:
        - gosec
      text: "G304:"  # File path provided as taint input

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gocritic
      severity: warning